### ISSUE TITLE
Implement cache module for Redis

### ISSUE THREAD

**Issue by xvrl** [apache/incubator-druid#1927]
Can probably reuse most of the Memcached code.

@estliberitas offered to work on this.

**Comment by estliberitas** [comment]
Testing right now.

**Comment by estliberitas** [comment]
As far as I understand it, in order to implement a separate cache module which works with Redis, we should move `CacheProvider`, `Cache`, `CacheStats` to `druid-common` module, correct?

If so, we would need following changes:

1. Add `server-metrics` as dependency to druid-common thus `Cache.doMonitor(...)` has `ServiceEmitter` as argument (or refactor this to not depend on `server-metrics`)
2. Remove `@JsonSubTypes` from `CacheProvider` and instead register subtypes in `CacheModule` via exported Jackson module -`SetupContext.registerSubtypes(...)`.

I have a problem with backwards compatibility: since I moved `CacheProvider` to `druid-common` I can't set default implementation class in `@JsonTypeInfo` annotation. If there any way to setup default implementation from code or do something else to set `LocalCacheProvider` as default `CacheProvider`?

**Comment by estliberitas** [comment]
**UPDATE**: I just looked at code and found that `mysql-metadata-storage` module has `druid-server` as it's dependency. If so, then Redis cache module can have this dependency too and nothing above is needed, right?

Will I still be able to use `SetupContext.registerSubtypes(RedisCacheProvider.class)` in case that `@JsonSubTypes` over `CacheProvider` is left as is.

**Comment by xvrl** [comment]
@estliberitas yes, you can depend on druid-server to get the ball rolling on this. We can revisit later if that becomes a problem.

`registerSubtypes` should be enough to make it work yes, but you should test to see if you can stil use both memcached and redis. If not we might have to manually register all the cache types instead of using annotations.

**Comment by estliberitas** [comment]
@xvrl @fjy It may be an odd question, but, how can I create a custom build in current master branch?

With 0.8.1 it was simple with `extensions-distribution` module. Now it's removed, and I do not understand how can I create a build and include my new extension (resides in `extensions/redis-cache`) into it.

**Comment by gianm** [comment]
@estliberitas if you do a `mvn install` then that will build extensions into the `distribution/target/extensions/` directory.

**Comment by gianm** [comment]
The extensions system was reworked in #1638

**Comment by estliberitas** [comment]
@gianm I figured that out, but still can't understand how can I add my new extension to others that are bundled.

**Comment by guobingkun** [comment]
Hi @estliberitas, you can add an entry here https://github.com/druid-io/druid/blob/master/distribution/pom.xml#L95

**Comment by estliberitas** [comment]
@guobingkun Well, my extension is not on Maven (I'm currently developing it), is it OK?

**Comment by guobingkun** [comment]
@estliberitas , that's fine, pull-ups will pull from local repository.

**Comment by estliberitas** [comment]
@guobingkun Thanks, it worked!

**Comment by estliberitas** [comment]
@xvrl @fjy Hi, guys, please review code in referenced PR. Feel free to strictly criticize it as I did not code Java for almost 4 years.

**Comment by tutunci** [comment]
Hi,
is there any chance to have this module as 0.9 extension (If not already there and I didn't discovered) ?

Thanks
Maurizio
