### ISSUE TITLE
Any descriptions for bitmap index usage in Druid?

### ISSUE THREAD

**Issue by brucenan** [apache/incubator-druid#2020]
I known Druid use roaring bitmap as one of the bitmap index, 
I just want to known how druid mapping the provided data (for example, one column is md5 strings) to each position in bitmap object. 
I browse the source code, and still no find the indexing process. 
Could you please point out which codes do this job? or some details description? Thank you very much.

**Comment by sirpkt** [comment]
As I know,
bitmap generation code is in makeIndexFiles() of IndexMerger.java.
It is a little complicating because Druid does not update bitmap at ingestion time but generates bitmap at persist time.
Druid only updates IncrementalIndex(which does not have bitmap) on ingestion time
and if the number of rows in that IncrementalIndex exceeds some pre-defined number (as I know, default value is 500,000), it persists that to a file in local storage, which contains inverted index that has bitmaps for each dimension values.
And then, the file is restored in memory as a QueryableIndex, which has Columns that includes dictionary and bitmaps. 

I'm also newbie, so, there may be some misunderstanding :)

**Comment by brucenan** [comment]
Thanks @sirpkt , I've found that files. As I know, Druid create Segment files to store data and bitmap index. From your description, max line is 500,000. So if there are 1,000,000 lines of data, does Druid generate two Segment files? My interesting is How druid calculate a special measure by dimensions with two Segment files at same time. Is it necessary to merge all related Segments files to ONE big Segment object?
