### ISSUE TITLE
Shade problematic dependencies in Druid

### ISSUE THREAD

**Issue by kupferk** [apache/incubator-druid#2093]
There are recurring problems with the Druid Hadoop Indexer because of dependency conflicts between Druid and Hadoop (Jackson and Guava come to my mind). I would propose to shade the problematic jars, so Druid won't interfere with Hadoop any more.

I am by no means an expert on this topic, but I'd like to take over this task. My current idea looks as follows:
- Create a new Druid module containing the shaded jars (maybe druid-shims ?) where the offending classes are relocated into a new package (io.druid.shims.*)
- Add dependency to other Druid modules to this special shim module
- Replace all occurances of shaded classes with new package name, i.e. com.google.guava.\* would be repalced by io.druid.shims.guava.*

Does this make sense? Is this the correct way to go with shading? Any comments and ideas are welcome.

**Comment by navis** [comment]
:thumbsup:

**Comment by drcrallen** [comment]
Speaking from experience, extensions which depend on other extensions tend to get tricky. With how the module classloader isolation works in Druid you often cannot access the classes cross-extension in the ways that you would hope. As such, it would make more sense to have anything that is shaded be in the system classloader (or at least the same classloader as all the other core druid stuff).

This is very much so worth discussing on how to best approach the "how can we upgrade our libraries independently of other toolsets" question

**Comment by kupferk** [comment]
Thanks for your feedback @drcrallen . Just to avoid confusion on my side: My idea was not to create a new Druid extension, but instead to build a simple basic Java module (the term 'module' as in Maven module) containing all the shaded stuff. The core of Druid (and probably then also all extensions) would then have that java package as some simple build dependency. I assume that then this module would be present in the classloader of the Druid core stuff - or would there still be a problem? I will investigate into the usage of classloaders in Druid... that's also some new terrain for me.

I hope that I will have some time for first experiments at the end of the week.

**Comment by drcrallen** [comment]
The "ideal" solution would be to have the classloaders properly isolated such that different java library versions can be used in different parts of the data stack... but the tricky part there comes in when they have to communicate across classLoaders. Otherwise you'll get into a case where you get an error where class `x.y.Z` cannot be assigned to class `x.y.Z`... which is very confusing to see in an error until you realize they were loaded through mutually exclusive classloaders.

Has anyone out there been able to solve hadoop library problems without resorting to shading?

**Comment by kupferk** [comment]
That's a good point. Give me some time to think about that, I really need to get a better understanding which module or extension first use specific classes and where exactly the Hadoop dependency jumps in. I believe it should be possible to perform isolation via class loaders - but yes, it could get tricky.

**Comment by kupferk** [comment]
I have been thinking a little bit about solving the issue with some ClassLoader magic. One big issue here is that the mappers and reducers will be instantiated by Hadoop, of course the offending jars from Hadoop then are already present in the ClassLoader. 

So one idea would be to implement "delegating" mapper and reducer classes, which first setup a properly build ClassLoader with Druid provided jars of the problematic classes. This ClassLoader would also need to be implemented such that it first looks into its own list of jars and then delegates to the parent class loader (I think the normal behaviour is the opposite way round). At least it should have a blacklist of classes which should not be delegated to its parent.

Then those delegating mapper and reducer could instantiate the real Druid mapper and reducer using its special ClassLoader. The map/reduce methods of the encapsulting mapper/reducer then would delegate the work to the loaded mapper/reducer.

Any thoughts about that? Does this make sense to anybody?

**Comment by drcrallen** [comment]
ASSUMING there are two magic ClassLoaders whose parents are the System classloader... and one ClassLoader is druidClassLoader, and the other is hadoopClassLoader... where the druidClassLoader has all the stuff that druid jars link to, and hadoopClassLoader has all the stuff hadoop things link to, then I would *think* you would want any hadoop classes loaded by ONLY the hadoop classloader, and to have those classes only be aware of their library compatible versions. And any druid classes to ONLY call druid classloader stuff.... EXCEPT for hadoop classes, which will need to be loaded from the hadoopClassLoader.

https://issues.apache.org/jira/browse/MAPREDUCE-1700 is worth a read-through.

Since hadoop has some level of OSGi awareness (I have not looked into it much) it may be easier to figure out how to bundle the druid jars in an OSGi friendly way.

**Comment by kupferk** [comment]
Please excuse me for the silence, I have been busy with some other work to do.

I think I found a valuable Hadoop configuration property called "mapreduce.job.classloader". This is set to false per default. Programmatically setting it to true just helped me in a different project to use some older version of protobuf libraries than the ones used by Hadoop. So setting this property might be worth a quick try.

I will try to look into that.
