### ISSUE TITLE
Suggest to support dynamic addition/removal of namespace in lookup

### ISSUE THREAD

**Issue by sirpkt** [apache/incubator-druid#2273]
Currently, namespace configuration of namespaced lookup is static as it should be specified in the runtime properties file.
I think it would be beneficial if we can also add namespace dynamically
because we can add data source dynamically and we may find that new namespace to lookup is needed with that data source.

**Comment by sirpkt** [comment]
At first, I thought NamespacesCacheResource is good point to add functionality to add/remove namespace through Json.
However, with that approach, I should post namespace to all brokers, peons, and historical nodes,
which seems naive.

**Comment by drcrallen** [comment]
I'm working on this currently.

**Comment by drcrallen** [comment]
Part of the issue here is that the concept of "service" exists... but the concept of "capacity" or "feature" does not. So part of my proposal will be an experimental aspect which allows for "feature" discovery for features that rely on ID based stuff (hosting namespaced lookups, hosting segments, etc). With the intent that the Coordinator make appropriate requests to all feature holders on what their configs should be.

The coordinator would then be the "what is the appropriate state?" holder, and ask the nodes with features to adjust their state accordingly.
