### ISSUE TITLE
Example start scripts in bin/node.sh do not warn if `log` and `pid` directories do not exist

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3124]
The example shells do not auto-create the log and pid directories.

The lack of log auto-creation causes a fresh tarball to fail to launch at all

The lack of pid directories makes the start/stop functionality not work. The instance launches but you cannot stop it with a `stop` command, and there is no guard against running multiple instances.

Manually creating the instances fixes these errors, but they should be auto-created.

**Comment by fjy** [comment]
@drcrallen nice catch. We shoudl fix this

**Comment by gianm** [comment]
@drcrallen did you run `bin/init`?

**Comment by gianm** [comment]
I tried this myself, I believe the issue you noticed is due to not running `bin/init` – I saw similar issues when I didn't run it, but things were OK when I did. Another note: as written, those "x.sh" scripts do not actually work with the quickstart, because they hardcode "conf" rather than having a switch between "conf" and "conf-quickstart" (not clear if this is intentional).

I think these are ok for 0.9.1 because,

- the quickstart calls out that running `bin/init` is something one should do
- the quickstart (or any of the docs) never mention the "x.sh" scripts

So I am inclined to move this to 0.9.2, as an improvement rather than a bug fix.

**Comment by fjy** [comment]
@gianm I spoke with @drcrallen and he didn't run bin/init

**Comment by gianm** [comment]
okay, I'll change the tags then. anyone interested, please chime in if you feel this should be a blocker for 0.9.1.

**Comment by drcrallen** [comment]
yeah, sorry, I didn't have a chance to double check this over the weekend. Let me check it now

**Comment by drcrallen** [comment]
Correct, my bad. Will update description and master comment a bit.
