### ISSUE TITLE
Add a "druid" deep storage. 

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3151]
This ask is that a deep storage implementation be able to draw from a druid replicant FIRST before trying to pull from some other deep storage.

Since one other copy is commonly somewhere in the cluster, the only time a "non-druid deep storage" should need to be hit in a MVP implementation is when batch fixup runs. In future implementations the batch fixup could potentially transfer the data directly to druid as well.

It is highly suggested that checksumming https://github.com/druid-io/druid/issues/3150 be implemented first.

**Comment by xvrl** [comment]
@drcrallen can you clarify what kind of use-case / problem is this trying to address?

**Comment by pdeva** [comment]
one use case is to reduce data transfer costs from S3. 
currently druid is constantly hitting s3 and downloading segments all the time. 
Since our cluster resides outside of AWS, we get a massive data transfer bill.
If it was pulled from another replica most of the time, the bill would be much, much lower.

**Comment by pdeva** [comment]
bump

**Comment by himanshug** [comment]
@pdeva not sure when this will close but if AWS bill is too much then consider using NFS as deep storage. I haven't tried it but can't see why it wouldn't work. There might be few bugs but they would be easy to fix I think.
