### ISSUE TITLE
[Feature]MultiLine Kafka Message in Kafka Indexing Service

### ISSUE THREAD

**Issue by akkapur** [apache/incubator-druid#3439]
As a user, I want to combine multiple rows of data interleaved with a newline character, within the same kafka message and have the Kafka Indexing Service split up the message on consumption and index the individual rows.

So if the message looks like, 
**time1,value1,value2,value3**\n**time2,value4,value5,value6**\n**time3,value7,value8,value9**

There will be three rows ingested.
time1,value1,value2,value3
time2,value4,value5,value6
time3,value7,value8,value9

The example shown is for CSV lines, but it could apply to TSV, Json, aswell.

This would allow the user to make fewer calls to Kafka Servers.

**Comment by gianm** [comment]
There's a trickiness here with ensuring exactly-once ingestion: what happens if 2/3 of the messages are indexed and then a threshold is reached that triggers a disk persist or a publish to deep storage? I think either we would have to do some work to make sure only complete sets are persisted to disks, or we have to track "offset within an offset".

As an aside, @akkapur, what do you mean by "this would allow the user to make fewer calls to Kafka"? The Kafka producer can already batch messages, so it should be able to send those three records as one compressed batch even if they are three different logical messages.

**Comment by gianm** [comment]
See also #4373.
