### ISSUE TITLE
Interruptible QoS for query processing thread pools

### ISSUE THREAD

**Issue by drcrallen** [apache/incubator-druid#3810]
There are times when a large query can take all processing threads on a historical node, and a "low work" query comes in which needs a processing thread quickly (higher query priority). In the current query processing queue, the high priority query must wait for the processing thread pool to free up a worker slot before being able to do any work.

This ask is that a smarter QoS solution be in place to prevent a single, long-running query from hogging all the processing threads in the face of higher priority queries.

One solution is to allow processing to be interrupted at the JVM level.

Another solution could be to allow thread prioritization at the kernel level to do the preemption/interruption, and have separate processing thread pools for separate priorities (based on some rule set).

**Comment by gianm** [comment]
Some things to think about:

- If we do allow processing tasks to be preempted, how does resuming them work? Do they start over from the beginning or do they save state somewhere and resume where they left off? If they start from the beginning, this may involve a lot of extra work being done if tasks get preempted frequently. If they resume where they left off, we need somewhere to put their state (the contents of the processing buffer and the continuation of the processing thread) as well as some way to avoid saving too much state and running out of resources.
- Do we still have a limit on the max number of concurrent queries, which is currently given by `druid.server.http.numThreads` for most queries and `min(druid.server.http.numThreads, druid.processing.numMergeBuffers)` for groupBy v2? The max number of concurrent queries (_including_ preempted queries) needs to be limited because we don't have an infinite amount of space to store partially merged results.

Having separate thread pools (and memory pools and concurrent query limits) per priority level is one way of solving those problems. The downside is this means we need to reserve some memory for high priority queries, even when there are none happening.

**Comment by drcrallen** [comment]
@gianm do the memory pools need to be separate? Can a single common StupidPool for processing buffers be used?

**Comment by gianm** [comment]
There's three kinds of memory/storage pools I'm talking about:

- processing buffers (the `@Global StupidPool<ByteBuffer>`), all are the same size and at most `druid.processing.numThreads` will exist at any one time.
- merging memory (for topN and groupBy v1, it's the JVM heap; for groupBy v2, it's the `@Merging BlockingPool<ByteBuffer>`), size depends on query type and the number that exist at once depends on the number of concurrent queries.
- on-disk spilling space (only used by groupBy v2), which is limited by `druid.query.groupBy.maxOnDiskStorage` and the number of concurrent queries.

It should be fine for the processing buffers to all come from the same pool as long as some other mechanism exists to prevent unbounded numbers of buffers being allocated at the same time.

All of those three pools have the same basic problem though, which is what do you do with memory/disk resources you've allocated to a low-priority query when a high-priority query comes in. You could keep them allocated to the low-priority query, which implies you'll need to reserve some resources ahead of time for high-priority queries, otherwise there might be none left. Or you could deallocate them, which implies that low-priority queries will either get canceled or will need to re-do some or all of their work. Or you could save them to disk and restore them later, which works for the memory pools, but then you have to have a plan for what to do when you run out of disk space.

IMO, the simplest solution varies based on whether low or high priority queries are "normal".

If high priority queries are normal but there are a few low priority queries from time to time, then probably reserving resources for high priority queries works best: let high priority queries use _all_ memory but low priority queries only use X% of it. This means low priority queries can't use the full power of the cluster, but that's fine because most of your queries are high priority anyway.

If low priority queries are normal but there are a few high priority queries from time to time, I think de-allocating resources works best: if a high priority query comes in, let it grab resources that are currently used by a low priority query, and force that low priority query to start over when the high priority query is done. This means that some low priority queries will need to redo some work, but that's fine because there aren't that many high priority queries so this won't happen very often.

If you have a lot of both kinds of queries, that's tougher :)

Some other thoughts:

- If the expected workload involves a lot of concurrent low priority queries, you may need to tackle the query concurrency limit too, which is imposed by the jetty thread pool size: `druid.server.http.numThreads`. If those are all taken up by low priority queries, then processing pool QoS is irrelevant since the query will not even get that far. Keeping in mind that lifting this limit will create more memory pressure in terms of memory used for merging results.
- The problem is a lot simpler if you assume that memory for merging results is effectively "unlimited". Then you only have to worry about one of those three pools (the processing buffers). This is probably a valid assumption for timeseries. It may even be valid for topN if you have some reasonable limit on the number of concurrent queries and on thresholds. It is probably _not_ valid for most groupBy workloads.
