### ISSUE TITLE
No way to get roaring bitmaps on merged segments?

### ISSUE THREAD

**Issue by andy256** [apache/incubator-druid#3918]
In druid 0.8.2, you could specify `druid.processing.bitmap.type=roaring` to get roaring bitmaps in indexing, and in segments merged by overlord tasks. However, in druid 0.9.x, that seems to no longer work, and additionally, there seems to be no way to force it to use roaring bitmaps as the `indexSpec` field is empty in the coordinator merge task, so it just uses the system default (concise).

So we have roaring bitmaps for a little while, but then the index merger comes along and replaces them with concise ones.

Please tell me I'm wrong and there's a way to configure this.

**Comment by gianm** [comment]
@andy256 manually issued "append" and "merge" tasks can be given an "indexSpec" and you should be able to get roaring bitmaps that way. I think there's currently no way to customize that for the ones you get from druid.coordinator.merge.on, but you're right, ideally there should be. If you're willing to contribute a patch, I'd try something like:

- add a property `druid.coordinator.merge.indexSpec` that accepts a json-formatted IndexSpec, in the manner of other json-formatted properties like `druid.extensions.loadList`.
- update io.druid.server.coordinator.helper.DruidCoordinatorSegmentMerger to submit this indexSpec along with the "append" tasks it creates

**Comment by andy256** [comment]
The `ClientAppendQuery` object doesn't accept an `indexSpec`, though, only `dataSource` and `segments`... additionally, it shows up in the overlord tasks with a "merge_" task id, not "append_" even though it should be an "append_" task. I'm quite confused by this code path.

**Comment by gianm** [comment]
What's going on here is:

- ClientAppendQuery is the "client-side" version of the AppendTask. It exists so the IndexingServiceClient and its users (which are in druid-server) don't need to depend on classes in druid-indexing-service. It just has to serialize to something that can be deserialized into an AppendTask. It only has dataSource and segments right now because that's all anyone needed, but if you add an indexSpec (or any other thing that is also a parameter of the AppendTask constructor) then that should work too.

- AppendTask extends MergeTask and inherits the naming behavior, hence starting with `merge_`

**Comment by andy256** [comment]
Ah, I see. I was missing the fact that AppendTask was derived from MergeTask. I'll give it a shot.
