### ISSUE TITLE
After updating to Java 8, replace inefficient Map use patterns

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#4034]
Current code sometimes uses inefficient or unsafe patterns, because Map and ConcurrentMap interfaces in Java 7 lack such methods as putIfAbsent(), compute(), computeIfAbsent(). This issue is not to forget to review and update such places after the project moves to Java 8.

**Comment by leventov** [comment]
E. g. https://github.com/druid-io/druid/pull/3889/commits/77c3981ed8328b00955979a2e476ab3bd1457b5c

**Comment by leventov** [comment]
Except for collections from fastutils, because they doesn't have specialized forms of those methods yet.

**Comment by incaseoftrouble** [comment]
Just a heads-up since this might be relevant for you: I am currently working on solving the referenced fastutil issue. I summarized the Java 8 migration in https://github.com/vigna/fastutil/issues/64 and added some preliminary work in https://github.com/incaseoftrouble/fastutil/commit/bad6ffa147d9017350973a99f631a03858de2ea6 . Feel free to comment / contribute in any way!
