### ISSUE TITLE
Why the Overlord's page is titled Druid Indexer Coordinator Console 

### ISSUE THREAD

**Issue by hzy001** [apache/incubator-druid#4050]
![overlord](https://cloud.githubusercontent.com/assets/9567254/23893254/c102e096-08d8-11e7-976e-670fc497260a.png)

As the above picture shows, why the Overlord's page is tigled Druid Indexer Coordinator Console?

**Comment by erikdubbelboer** [comment]
I guess because it shows the coordination of all index tasks.

**Comment by hzy001** [comment]
:1st_place_medal:

**Comment by vogievetsky** [comment]
This was fixed a long time ago, in Druid 0.11 or 0.12 I believe.

**Comment by clintropolis** [comment]
Actually, it appears [this was still true in 0.13](https://github.com/apache/incubator-druid/blob/0.13.0-incubating/indexing-service/src/main/resources/indexer_static/console.html#L26) but was [fixed with the introduction of the new web console in 0.14](https://github.com/apache/incubator-druid/blob/0.14.0-incubating/web-console/console.html#L26)
