### ISSUE TITLE
Coordinator Console : Suggesting Changes

### ISSUE THREAD

**Issue by arpankhagram** [apache/incubator-druid#4145]
Hi Team, I feel there is a need to add few columns on coordinator console for "Complete Tasks - Tasks recently completed" tabular view. (snapshot of my coordinator console attached)

1. If there is any task which fails - it;s better that is displays which middleManager has processed that particular task so that we can directly go on that node to check the logs. There is a columns called location host which is always displayed as null in my case for completed tasks. Kindly let me know if i might have missed any configuration for the same.

2.It's better to keep start and end time of the completed task (or only one of them)

3. I am not able to logs [ hyperlink] for completed tasks.

![image](https://cloud.githubusercontent.com/assets/20059251/24673460/55f93342-1970-11e7-853a-72a5a12abb4e.png)

**Comment by arpankhagram** [comment]
Hi Team, I'm not quite sure but shall I open pull request to progress this ?

**Comment by pjain1** [comment]
Your observation is correct the console does not show information about the task location after it is done. Currently the information like start time, task location is not saved when the task is done. Only task id, status, duration and task payload are saved. 

As far as I know, I think the reason being when middle manager nodes were introduced the idea was they are considered ephemeral in the sense new MMs can be spawned on demand and when not required they can be taken down. Thus, it does not help much to save task location information.

However, you can still access the logs from the console, you will need to send them to deep storage so that they can be streamed from there on demand. See `Task Logging` section here - http://druid.io/docs/latest/configuration/indexing-service.html

**Comment by arpankhagram** [comment]
@pjain1 So is it possible to display location and start/end time on UI as per current code architecture ?

**Comment by pjain1** [comment]
Its definitely possible. I am not very familiar with the task management part of the code but after having a quick look it seems like `TaskStatus` could be changed to include location information so that when the task is done, the location information can be stored in metadata store along with the status, id and duration. 

However, again if the task logs are sent to deep storage (HDFS/S3/Azure etc) then they can be accessed from the console directly. If you must store the logs locally then one trick is to use any parallel ssh tool to `ls` for a specific task log that you are looking for in `druid.indexer.logs.directory`.
