### ISSUE TITLE
Does Druid fit my olap requirements? 

### ISSUE THREAD

**Issue by javcly** [apache/incubator-druid#4224]
Hi all,

I am evaluating Druid for our new OLAP system which is a saas platform for our customers to load product and product sales data into the system then analyze. The analytics requirements are simple, aggregate sales data by product categories and  attributes  in  selected time frames. Analytic results need to be near realtime(within a minute). 

The estimated data sets are 10+ million sales records and 3-5 million products, 1000+- categories and 100+- attributes

A product has categories (shirt, shoes, T-shirt, accessories,etc)  and attributes ( size,color, year, season,etc). Categories and attributes can be added, removed, updated,  and the report data for the affected products should be updated as well.  Also, past sales data can be altered, then the report data should be updated as well.   Categories and attributes updates  are not frequent,  new sales data can come in every second, past data can be updated or added if missing, but not as frequent. 

Druid seems to be perfect choice on the query side, but I am not sure about data updates as Druid segments are immutable. As far as I understand,  perhaps I could use Druid to do the followings to handle data changes:

1. When a category or attribute is added or removed, find affected products,  use lookups update dimension values
2. When a sale data record is changed, reindex the whole segment the data is in
3. When a product's attribute value or category is changed, eg. size 8 changed to size 9, category Shoes changed to Shirt, use lookups to update dimension values.

I am not sure if it is the right solution, please correct me if i am wrong or point me to the right direction. 
Thank you all in advance.

**Comment by sascha-coenen** [comment]
Hi, I might not be the best person to answer your questions, but perhaps you might find the following helpful:
we use Druid for analytical queries and have much larger datasets that Druid run fine on.
For your usecase, we decided to go with lookups. Since the data you need to join in is in the millions, perhaps you need to use the lookups-cached-single extension.

Since you don't have a large dataset, perhaps using a regular relational database is a better fit, especially if you have a lot of writes. Vertica might suit you well. 
In case you'd like to use Druid, there are some caveats with lookups. They are experimental and if used, you need to be careful in cases your lookups are not in a 1:1 relationship with the keys. For instance, we have a lookup that maps a product Id into one of a few product categories.
This lookup works well for splits (i.e. groupings) and we don't notice a performance hit there. However, if a user filters on that lookup definition and innocently selects a single category, then Druid reverse-looks-up all the product IDs and translated the original query into one that now has millions of filter terms. 
Therefore, we try to stick to 1:1 lookup definitions which just rewrite Ids to nice labels. 
There's also support for joins in the works in which smallish datasources get loaded to each cluster node and can then be joined into the master datasource.

Perhaps some of your data needs to receive updates more frequently than other data. You could segregate the data into separate datasources and issue union queries across the datasources.
