### ISSUE TITLE
Support for speedy filtering on very high cardinality dimensions

### ISSUE THREAD

**Issue by viblo** [apache/incubator-druid#4556]
I have a very high cardinality dimension (IPs that in my case are more or less unique). I want to be able to filter on this dimension when I do my queries in a way that doesnt kill my performance. 

Example data:

Type | IP | Uses
--- | --- | --- 
1 | 10.0.0.1 | 3
1 | 10.0.0.2 | 5
1 | 10.0.1.0 | 3

Example query: TopN on the dimension Type for metric Uses with IP in this range: 10.0.0.1 - 10.0.0.255. This query would return 8 Uses for Type 1. 

The ranges can change for each query, and can also be a single IP. I am interested in not only TopN queries, but also timeseries and groupby.

The naive way to do this is to just use the IP directly, but as far as I understand it its not a good practice to have a dimension that have very high cardinality as in this case. In my case I would be ok with a approximate solution, for example a bloom filter (or maybe theta sketch could do this?)

(I asked about it on druid-users, and got the suggestion to report it as an issue here. https://groups.google.com/forum/#!topic/druid-user/ME-Ev5bf-qg)

**Comment by gianm** [comment]
I'm assuming you have this loaded as a string column now, since that's the default for dimensions. A few things could potentially help here.

1. You don't say what kind of filter you're using, but for range and prefix filters on string columns, "bound" and "like" perform substantially better than the alternatives. In your example LIKE "10.0.0%" should work best. For running these on IPs, it can help to store them in 0-padded hex encoding rather than dotted decimal, since that will make any subnet range or prefix search doable with a "bound" or "like" filter.
2. Roaring bitmaps tend to work better than Concise for unioning large numbers of bitmaps, so you could try switching to those (at indexing time using `"indexSpec" : { "bitmap" : { "type" : "roaring" } }` in your tuningConfig).
3. If you don't have any IPv6, you can also try loading the IP column as a "long" rather than the default of "string". Longs are currently unindexed in Druid, which may or may not hurt depending on your queries. So they tend to be faster sometimes and slower sometimes depending on your query. If you have IPv6 then this isn't doable since we don't have a numeric type that wide.

**Comment by viblo** [comment]
At the moment I only have a thetasketch of the IP to count them. To be able to filter on IP is a new requirement and Im looking into what options there are.

**Comment by gianm** [comment]
Ah okay. Well, in that case, try doing either a "string" or "long" dimension. One of them should work best for you.

**Comment by himanshug** [comment]
I don't think you can do it with information stored in thetaSketch which is just maintaining hashes to do unique counts.
this would definitely require storing IPs into a dimension column and using the inbuilt selector/bound etc filters.
