### ISSUE TITLE
bitmap expand too much

### ISSUE THREAD

**Issue by yiguolei** [apache/incubator-druid#4577]
Hi guys, if all dimensions are integers, does bitmap expand too much? 
for example, if all columns in a segment are integers, the bitmap size maybe equal to the actual datasize. Does druid  think about this?

**Comment by leventov** [comment]
Unclear what you are asking. What do you mean by "bitmap expand too much"? "columns in a segment are integers" -- you mean integer (actually long, because Druid doesn't have 4-byte integer dimensions now) dimensions or metrics? "bitmap size maybe equal to the actual datasize" what is "bitmap size" and "datasize" here?

**Comment by yiguolei** [comment]
@leventov 
the bitmap size = cardinality (number of distinct values in segment file) * number of rows / 8. 
the data size = avg row size * number of rows.
If every dimension has a bitmap index, maybe the bit map size is larger than the data size. For example, there are 50000 rows in a segment file, every row have 10 long value dimensions and 1 float metrics and every dimension have 1000 distinct values. In this case, there will be 10 bitmaps  and every bitmap's size = 1000 * 50000 /8 and the size is:
 the bitmap size =   10 * 1000 * 50000/8 = 62.5mb [not consider about compression of bitmap, like roaring] 
the data size = 50000*(10*8 + 4) = 4.2mb
You can see, the bitmap size is larger than the data size. It may waste lot of storage.

**Comment by leventov** [comment]
@yiguolei is it more like a theoretical question or you hit this in your workload somehow?

Note that Druid currently doesn't compute bitmaps for long-typed dimensions, only for string-typed dimensions (it was the only available type of dimensions until recently, long-typed dimensions is a recent addition.)

Not considering bitmap compression is wrong, because it reduces the footprint required for bitmaps for high-cardinality dimensions dramatically. Note that "concise" bitmap compression algorithm could still be preferable over "roaring" in this case, because it achieves much better compression. However this area is very far from being optimized well in Druid, a lot of changes are possible that would allow better compression _and_ better performance, e. g.  #3882

Generally you cannot say that some format is "waste of storage", because there is always a tradeoff between how much do you precompute in the segment (bitmaps, indexes, etc.) and therefore the segment size increases, and how fast you can perform queries. See https://en.wikipedia.org/wiki/Space%E2%80%93time_tradeoff

**Comment by yiguolei** [comment]
@leventov 

> long-typed dimensions is a recent addition
Do you have some design doc about index on long-typed dimensions?  It will also use bitmap index or other type indices?

**Comment by leventov** [comment]
@yiguolei see #2426
