### ISSUE TITLE
How to avoid a "join" in Druid?

### ISSUE THREAD

**Issue by donpinkus** [apache/incubator-druid#4621]
How should I handle the below query in Druid? 

In classic sql, it would be a simple sub-query & a JOIN. (Don't worry, I understand the reasons we don't support JOINs in Druid explained in the spec doc) So I'm wondering, for those experienced with Druid and faced with this problem, what would you do?

### Data Sources

**user_purchases**
```
first_name   last_name    purchase_amount
--------------------------------------
james        smith        1234
kate         johnson      444
```

**user_events** (an active user is one with a "sign_up", but no "deactivate" event.
```
first_name   last_name    event
--------------------------------------
james        smith        sign_up
kate         johson       sign_up
james        smith        deactivate
```

### Queries:
Here is the sloppy way I would currently do it:
1. Get all "first_name" + "last_name" combinations from user_events that do NOT have a deactivate event.
2. Use some code and turn the resulting (first_name, last_name) pairs into a giant filter clause, possibly with 1000's of conditions. Then do a query on `user_purchases` using this filter clause.

**Comment by drcrallen** [comment]
(Major caveat, we do *not* have queries quite like this in production, so this is speculation)

Couple of things to note:

Your first name + last name is not really an identifier. You have some underlying information you are hiding (unique identifier) whose property is a first name and last name. Unless you really are trying to sum the purchase amounts of all people who have a first and a last name (and no other name of record) which happens to equal the tuple `("james", "smith")`, you might want to consider finding a way to store the underlying data with the events, and consider things like first and last name as metadata about the "real" event data (unique id) that needs to be handled either at ingestion time through ETL, or query time with QTL.

Lets look at the case where there's really a unique ID underneath, and you want information related to the unique ID.

For the total purchase amount, it becomes pretty straight forward. You simply sum the total purchase amount by the unique ID. This becomes more complex if you have something like "was on premium plan" or similar. In such a case the state of the "plan" is also related to the purchase item, and becomes much more complex to analyze. You should be able to look at a particular user ID, and look at the different plans each user ID was on, and do the purchase amounts that way if such a calculation is needed (or look at the different plans and look at the user IDs per plan).

If you want to do a state accumulation, you are going to have a very odd time in Druid due to the eventual consistency nature of the data store. But let's say for the sake of argument that its OK and you have some time to make sure the state is consistent. In such a scenario it should be possible to process a "sign_up" event as a 1 and a "deactivate" as a 4, then if you add them together by unique ID you should get 5. If you do not get 5 hopefully you get 1. If you don't get a 5 or a 1 then you hopefully have a 0 (never seen) or else have a problem (duplicate or error events). If you allow for repeat signups you can either have new user IDs or come up with something more complex.

State transitions (unknown --> signup --> inactive) are something that have been asked about before, but I don't know of any particular group that has attempted to solve it in Druid.
