### ISSUE TITLE
datasource created by kafka supervisor is not presented in coordinator UI

### ISSUE THREAD

**Issue by mazorigal** [apache/incubator-druid#4715]
Hi,

when we submit kafka supervisor task, until the first time data would be persisted in the deep storage, the coordinator UI do not show that datasource, although the datasource is queryable almost immediately after the supervisor starts.

Thanks,

**Comment by b-slim** [comment]
Yes true, I have noticed that.  @gianm anyone is working on closing this gap from your side?

**Comment by cartershanklin** [comment]
This also affect Superset, which cannot see the datasources until they are visible in the coordinator.

**Comment by gianm** [comment]
I wouldn't call it a bug in Druid. The datasource _will_ show up in the broker datasource list, which is the list of queryable datasources. A tool like Superset should be using that broker API rather than the coordinator API.

The reason it doesn't show up in the coordinator UI is that the coordinator is in charge of published segments and historical nodes, and at this point, the segments haven't been published yet. So as far as the coordinator is concerned, the datasource doesn't exist.

That being said it would be more user-friendly if these queryable but unpublished datasources showed up in the coordinator UI anyway. So it would make sense to add them (although we should be careful of which API we add them to: they shouldn't show up in metadata-store-specific APIs). To your question @b-slim -- we aren't working on that from our end right now.

**Comment by b-slim** [comment]
@gianm as per druid docs one of the coordinator endpoint is listing the datasource `/druid/coordinator/v1/datasources` in addition to that the coordinator UI suppose to list existing datasources and let you define load/drop rules. So IMO it is a bug thought

**Comment by gianm** [comment]
I think the coordinator UI uses `/druid/coordinator/v1/metadata/datasources`. That one shouldn't return the unpublished datasources (it should only be querying published metadata).

But I think there is another coordinator API `/druid/coordinator/v1/datasources` that checks for queryable datasources rather than published ones. Maybe the UI should call both and combine the results into one master list. Or maybe the coordinator should have a new API that returns both, and the UI should call that. The docs should also be a bit more clear as to what the APIs are supposed to do.

**Comment by gianm** [comment]
I guess the thing is that there are some datasources that are _published_ but not _queryable_ (this can happen if your historicals are having trouble loading them). And there are some datasources that are _queryable_ but not _published_ (this can happen with new realtime datasources, where nothing has been published yet). So to give the whole picture the coordinator UI should be looking at both queryable and published datasources.

Tools like Superset though should probably just be looking at queryable ones.

**Comment by b-slim** [comment]
@gianm By published you mean stored on Deep storage or totally handed off ?

**Comment by b-slim** [comment]
by totally handed off i mean loaded and queryable via historical to be clear.

**Comment by gianm** [comment]
By published I mean written to the metadata store, and by queryable I mean served by some historical or realtime node.

**Comment by clintropolis** [comment]
closed by https://github.com/druid-io/druid-console/pull/21. Additionally, I believe the new web console should have the same functionality.
