### ISSUE TITLE
Illegal unquoted character

### ISSUE THREAD

**Issue by alexkappa** [apache/incubator-druid#4931]
Hello,

Druid is throwing the following exception when we ingest json files containing utf8 characters. I've asked in the user groups before but I have the feeling this is probably a bug in Jackson.

```
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal unquoted character ((CTRL-CHAR, code 19)): has to be escaped using backslash to be included in string value
 at [Source: { ... "Abcdef Vols � bas prix" ... }; line: 1, column: 1565]
```

The event is truncated, I can supply it privately if necessary. The column mentioned by the exception is the – character between "Abcdef" and "Vols" which is not printed in the logs.

I have [asked this question](https://groups.google.com/forum/#!topic/druid-user/yCHP01cAQ4A) in the druid user group but no luck.

We are using Go to serialize the JSON used by druid batch ingestion, which seems to leave certain unicode characters unescaped ([correctly as per the JSON spec](https://tools.ietf.org/html/rfc4627#page-5), anything between `\u0000` and `\u001F` is indeed quoted).  Here's a [Go playground link](https://play.golang.org/p/xirAX-mm3o) where the correct unicode points are encoded.

For example the following JSON will trigger an error: `{"a":"–"}`. The – is the en dash which maps to the U+2013 code point, but more utf8 characters are giving us trouble.

We're using druid 0.9.2 and we do the batch upload using the s3 extensions. Tranquility (version 0.8.2) however does not exhibit the same behaviour fortunately as our real time events are processed correctly.

There is a similar issue where another user requested configuring the flag to allow unquoted control characters, but I'm not sure this is the right way to go.

Thanks,
Alex

**Comment by alexkappa** [comment]
These issues seem to be related #1852 and #1840. It seems configuring the batch ingestion [`ignoreInvalidRows`](url) is the way to avoid this issue but we'll still be missing certain events.

**Comment by gianm** [comment]
@alexkappa, I tried reproducing this with the latest Druid and it seems to work ok. I used the wikipedia sample data that comes with the quickstart and edited one of the channel names to be a literal en dash, encoded in utf-8 as `e2 80 93`. It ingests fine and I can query if afterwards too.

```
dsql> select channel, count(*) from wikiticker where channel = U&'\2013' group by channel;
┌─────────┬────────┐
│ channel │ EXPR$1 │
├─────────┼────────┤
│ –       │      1 │
└─────────┴────────┘
Retrieved 1 row in 0.04s.
```

Is it possible you have some kind of encoding issue? If the en dash were encoded in utf-16 for some reason, that would explain this, since that would look like control characters to a utf-8 parser.

**Comment by alexkappa** [comment]
Hi @gianm,

Thanks for looking into this issue! 

I am not entirely sure I understand the encoding `e2 80 93`. I typically end up with a `\u2013` when serialising to JSON. With a little googling I could repeat that with [this online utf8 encoder/decoder](https://mothereff.in/utf-8#%E2%80%93) so I have the feeling I am misunderstanding something.

I can attach a gist with the exact files I'm trying and the exceptions I'm getting, perhaps I could give you some more context.

**Comment by gianm** [comment]
What I mean is that the character `\u2013` could be encoded in different ways. It could be encoded in utf-8 as three bytes, `e2 80 93` or it could be encoded in utf-16 as two bytes, `20 13`. JSON calls for utf-8 encoding and that's what Druid expects.

My guess is that your en dash is (incorrectly) encoded in utf-16, since the first byte `20` would be interpreted by a JSON decoder as a control character, which matches up with the error you got.

**Comment by gianm** [comment]
Opening your file in a hex editor, or using hexdump, should make it clear how the character is encoded.

**Comment by alexkappa** [comment]
I've opened it in a hex viewer and it seems to be encoded as three bytes.

![hex-view](https://photos-1.dropbox.com/t/2/AACjUlMDwj9KxnJHTuldul-63oUlyoiTKgpde6L5KwrPjw/12/48176547/png/32x32/3/1508504400/0/2/hex-view.png/EJO7_CQYnTUgBygH/QiMTfXTdu9IpmFDs7jZsY2pToKLELPrB85W5iwLJ_Zo?dl=0&size=2048x1536&size_mode=3)
