### ISSUE TITLE
There is no way to delete lookup tiers

### ISSUE THREAD

**Issue by tommargolis** [apache/incubator-druid#4940]
I see no endpoint that allows deletion of dynamic lookup tiers (i.e. user-defined tiers that are not the __default tier).  Please provide one or explain why no such endpoint can be provided.

**Comment by drcrallen** [comment]
`io.druid.server.lookup.cache.LookupCoordinatorManager#deleteLookup` https://github.com/druid-io/druid/blob/druid-0.10.1/server/src/main/java/io/druid/server/lookup/cache/LookupCoordinatorManager.java#L269-L270 could have a line that removes any tier from the config if the update is an empty hash map as a garbage cleanup kind of thing.

Can you expand on your use case where "empty" lookup tiers is a problem, and what the effect of that problem is?

**Comment by tommargolis** [comment]
Thanks for your quick response.  There's no problem with empty tiers yet. However, our tests create tiers as part of their normal processing, and we'd like to treat these as temporary tiers:  Create a tier, use it for testing, and then delete the tier.  We're concerned that problems may appear in the future as undeletable tiers build up through testing.

When you say "could have a line," does that mean: In the future, such a line could be added; or, currently, such a line may exist?

**Comment by prabakarankrishnan** [comment]
Is there any way to drop default __default tier in 0.10.1?

**Comment by himanshug** [comment]
@prabakarankrishnan it seems nothing has changed in this area. I will add necessary support soon.
