### ISSUE TITLE
Are query intervals inclusive or exclusive?

### ISSUE THREAD

**Issue by KenjiTakahashi** [apache/incubator-druid#5055]
Suddenly it became important :-).

When issuing, say, a `select` query (or any other, I just have this one hanging around):
```json
{
    "queryType": "select",
    "dataSource": "logdb_data",
    "dimensions": [],
    "metrics": [],
    "granularity": "all",
    "intervals": "2017-11-01/2017-11-05",
    "pagingSpec": {"pagingIdentifiers": {}, "threshold": 50}
}
```

what is the open/close interpretation of intervals?
It seems that it is left closed, right open. But I do not see it clearly mentioned anywhere in the docs and need definitive answer.

**Comment by drcrallen** [comment]
Left (start) is inclusive and right (end) is exclusive.

As a point of maintenance, I highly suggest specifying the timezone offsets in all your intervals, otherwise it is hard to keep track of what the client intended.

If you are on the west coast of the US, you are going to get results that vastly differ with a `-07` or `-08` time shift vs a `+0000` or `Z` specification.

It is worth noting that if the standard setup guide is followed then the interval timezone will default to UTC.

**Comment by KenjiTakahashi** [comment]
Great, thank you! Maybe it will be worth noting this explicitly somewhere in the docs?

Currently our system stores and retrieves all data in UTC always, so it shouldn't be problem. Thanks for the heads up, though :-).
