### ISSUE TITLE
[Proposal] Support ingestion data from RDBMS via Local Indexing feature.

### ISSUE THREAD

**Issue by himanshug** [apache/incubator-druid#5238]
In many cases, users have input data inside RDBMS and current approach is to dump it out on disk/hdfs and then use Druid's batch indexing mechanisms.

This proposal is to enable direct ingestion with Local Batch Indexing. Idea is to write a `SQLFirehose` that takes DB connection information where input data is stored and a SQL query to fetch data out. With this firehose, user can do Local Batch Indexing to achieve data ingestion into Druid.

To workaround the scalability limits of Local Batch Indexing, It is advised to trigger multiple such indexing tasks. For example, if 30 days worth of data is to be ingested into Druid then trigger 30 Local Indexing tasks each processing 1 day worth of input.

However, This proposal is not to enable same feature in Hadoop Batch Ingestion which would be nice too but independent.

**Comment by himanshug** [comment]
This was discussed in dev-sync and agreed upon.

**Comment by fjy** [comment]
👍 great!

**Comment by himanshug** [comment]
@jihoonson we're hoping to reuse `PrefetchableTextFilesFirehoseFactory` for this. Is there some inherent limitation that requires `PrefetchableTextFilesFirehoseFactory` to work on `TEXT` files only or is it written hardcoded to text data because that was the original use case?
For example, could it work with sql row set (with possibly byte[] columns) without unnecessarily convert data to text (and base-64 encoding for byte[] columns). In this world, I would imaging that parser to be used in `PrefetchableTextFilesFirehoseFactory` would be made configurable as well.

**Comment by gianm** [comment]
I guess it's just because it's the original use case. It would be nice to expand it to support Parquet and ORC files too.

**Comment by jihoonson** [comment]
@himanshug yeah, @gianm is correct. It was due to its original use case. It should be expandable for other file formats.

BTW, is this proposal for one time ingestion from RDBMS? Last year, I thought about the continuous ingestion from an RDBMS when data is continuously appended to that. For this use case, I think it can be easily implemented with the indexing service using the supervisor. Like kafka indexing service, the RDBMS supervisor keeps track of the offsets where the next task starts to read from. I think this proposal and the RDBMS indexing service what I thought can share some implementations. For example, the indexTask might be able to be used for both one time ingestion and continuous ingestion. @himanshug what do you think?

**Comment by himanshug** [comment]
@jihoonson yes, this proposal is about supporting ad-hoc batch ingestion where user would be explicitly submitting the local indexing task. users can automate and submit these jobs periodically based on data production inside their ETL pipelines that push data to RDBMS.
however, I would be in general be supportive about "continuous/automatic" ingestion from RDBMS if there is a use case and that helps users.
