### ISSUE TITLE
Support with high cardinality field

### ISSUE THREAD

**Issue by jorditamargo** [apache/incubator-druid#5535]
Hi,

We are suffering a big performance hit with druid due to a dimension in our data source which has a very high cardinality. We need that dimension but only if there are significant rows with that dimension, i.e. we should ignore/discard cases where this dimension with a unique value only appears once.

We thought about doing a two-step process: as we are inserting in realtime from Storm, when we receive the data we don't know if it's first appear or not, so we are inserting all, and once segment is closed after an hour, we execute a second query in a HIVE view to group manually the ones that only appear one time under something like "Unknown", and insert them again. The problem with this is that during the current hour there is still a degradation performance issue, but at least it works fine for data outside the realtime segment.

This is an in-house provisional solution, but we would like to know if someone can help with a more elegant one.

We are using version 0.9.2.

Thanks for your time.

**Comment by mkuthan** [comment]
We do exactly the same, for realtime ingestion all values for high cardinality dimensions are indexed without any special handling. Observed performance degradation is minimal due to the hourly segments and short duration (current day only).

On daily basis our system builds popular values dictionary, and this dictionary is used to replace tail values from high cardinality dimensions to "Varying" during nightly batch segment re-indexing. 

It would be really nice to have tail values "normalization" for high cardinality dimensions built-in into Druid indexing tasks.

**Comment by kyleboyle** [comment]
@gianm would you mind briefly mentioning what those techniques are, for reference? thanks

**Comment by mkuthan** [comment]
@gianm - Huge performance gain, especially if the segment is rolled up with minute to hour granularity. 

We apply long tail normalization for dimensions like request path in our e-commerce platform. Right now there are ~90 million active offers, every offer with it's own SEO friendly URL.

**Comment by kaijianding** [comment]
@jorditamargo If I understand correctly, you want throw away duplicate rows by judging by a specific dimension's value? If so, this PR #5693 may fix your need
