### ISSUE TITLE
Late update of HttpRemoteTaskRunnerWorkItem.State in HttpRemoteTaskRunner

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#5658]
Sometimes HttpRemoteTaskRunner.getRunningTasks() doesn't return running tasks which are returned by HttpRemoteTaskRunner.getWorkers(). As a result, in the overlord console, those tasks are seen in runningTasks of `Remote Workers`, but not in `Running Tasks`. But, they eventually show up in `Running Tasks` after a while.

**Comment by jihoonson** [comment]
@himanshug do you have any idea?

**Comment by himanshug** [comment]
this is expected behavior in `HttpRemoteTaskRunner` . It maintains a list of WorkerHolder instances one per MM which contains information about that worker and the tasks being run by that worker etc. `HttpRemoteTaskRunner.getWorkers()` is powered off of this list.

Additionally `HttpRemoteTaskRunner` maintains a globla map  &lt;taskId -> HttpRemoteTaskRunnerWorkItem &gt; which lists the tasks it has been asked to run or it detected from MMs on its startup while syncing with the MMs.

Usually the global list and the list of merged tasks from individual MMs will match but sometimes they don't and then `HttpRemoteTaskRunner` would ask specific worker to kill a task etc to rectify the situation and they would eventually converge.
For example, say MM1 was running task1, then MM1 died and didn't come back for 15mins, then `HttpRemoteTaskRunner` would mark task1 failed .... however if MM1 comes back and reports running task1 (say it was a restartable task) then `HttpRemoteTaskRunner` would ask MM1 to kill that task and it would never show up in `HttpRemoteTaskRunner.getRunningTasks()` while it might briefly show up in `getWorkers()` . There would be multiple such corner cases where a MM is doing something that does not match up to what it should be doing from `HttpRemoteTaskRunner` point of view.
In general, when MMs are being synced then that MMs specific WorkerHolder's list of task gets updated first and then the global list maintained by `HttpRemoteTaskRunner` and there could be a small lag before it starts to show up in global list but they would converge.

**Comment by himanshug** [comment]
1 min might be ok in failure cases where a MM was found doing something it wasn't supposed to and instructed to kill a task etc.
also , on overlord startup it might be ok as it would be discovering all the MMs and tasks they run and then update the global list of tasks based on those , calling listeners etc.

but, in general, the lag should just be getting the status update[s] from MM and then updating the global list, and 1 min sounds a bit higher for that.
https://github.com/druid-io/druid/blob/master/indexing-service/src/main/java/io/druid/indexing/overlord/hrtr/HttpRemoteTaskRunner.java#L1136 is the code that gets called to update the global list for each task status discovered from MMs.  there are locks there to ensure correctness but even with that it shouldn't take upto a min for global list to be updated.
do you always notice close to 1 min lag or it just happened once or something ?

**Comment by jihoonson** [comment]
@himanshug it doesn't always happen, but sometimes does. I'll dig this further to find more clues. Thanks for the detailed comments.
