### ISSUE TITLE
Period load rules should include the future by default

### ISSUE THREAD

**Issue by gianm** [apache/incubator-druid#5869]
We have seen problem scenarios like the following:

1. A user has load rules like: load 30 days, drop forever.
2. The user loads some data from slightly in the future (maybe some clocks are running a bit fast or slow) using streaming ingestion. This creates a segment with an interval that is in the future.
3. The coordinator disables the segment immediately upon noticing it (since it is not within the last 30 days).
4. The Kafka tasks time out during handoff (because the segments are never loaded).
5. And after that timeout, the data that was slightly in the future is _still_ not available!

It would be better, I think, if period-based load rules included an unbounded time into the future too. I bet this lines up better with users' intuitive idea of what "retain 30 days" means. Of course it could be changeable with some optional parameters (or a different kind of rule?) but I think the default behavior should be the intuitive one.

NB: A workaround to this is to use rules like "load 30 days" followed by "drop 1000 years" followed by "load forever". That has the same effect as what I am suggesting for the new default behavior: we'll drop anything older than 30 days, but retain the last 30 days and also anything that is in the future.

Related, but different: #5868.

**Comment by gianm** [comment]
Even though this isn't directly related to Kafka indexing, I gave it a Kafka tag since that's the kind of indexing most likely to be affected.

**Comment by teeram** [comment]
Nice idea @gianm.  Just wanted to mention that perhaps the `lateMessageRejectionPeriod` and `earlyMessageRejectionPeriod` found in the `KafkaSupervisorIOConfig` could go away in favor of new load rules.  Up to you guys of course, I just thought it might end up being a little confusing to have these configurable supervisor fields separate from load rules.

**Comment by gianm** [comment]
Hmm, I think there is still a use case for lateMessageRejectionPeriod / earlyMessageRejectionPeriod even if load / drop rule usage becomes more intelligent. Imagine having a 90 day load rule, but only wanting to load stream data if it's received within 24 hours. It could be useful if you need to do batch reprocessing on older data and don't want to worry about locks.

**Comment by QiuMM** [comment]
@gianm maybe add a new drop rule which will drop data older than a configured date, then if people we want to retain the last 30 days data, they can do like this: drop 30 days ago, load forever.

**Comment by jihoonson** [comment]
@QiuMM would you elaborate more on your idea? I'm not sure how's it different from the `PeriodDropRule`. Also, how does it fix this issue?

**Comment by jihoonson** [comment]
Is anyone working on this? If not, I think we can move this to 0.13.1.

**Comment by QiuMM** [comment]
@jihoonson currently, we can edit a `PeriodDropRule` like this:
```json
{
  "type" : "dropByPeriod",
  "period" : "P1D"
}
```
The period is from some time in the past to the current time, so this example will drop last one day data. I think `PeriodDropRule` is a impractical rule for it will always drop recent data. So people who want to retain the last 30 days data, they can not use this `PeriodDropRule` but have to do like this: load 30 days, drop forever. Then because of `drop forever` cause issues that @gianm have listed above.

Maybe we can remove the `PeriodDropRule` because I think few people would like to use it. Then add a new drop rule which will drop data older than a configured date.

**Comment by jihoonson** [comment]
@QiuMM thank you for the explanation. Now I got it. 

But, I'm afraid that it can introduce another issue. The purpose of load/drop rule is to control data retention which means how many data historicals should store locally. And as @gianm said, this problem mostly happens in stream ingestion which data size grows as time goes by. If dropRule works based on a fixed date, people might update the date for the dropRule periodically.

**Comment by jihoonson** [comment]
Ah, now I really get it. I thought you want to set a specific date for dropRule. It makes sense. Probably it's easier to use than the combination of the current loadRule and dropRule.

**Comment by QiuMM** [comment]
Yes, that right.

**Comment by jihoonson** [comment]
@QiuMM thanks! I think it makes more sense to add new rules like `LoadSince` or `DropBefore` rather than modifying existing rules. They would be more intuitive and easier to use than combining loadRules and dropRules to get the same effect. But I don't know what was the rationale for the current design of the load/drop rules. @gianm any idea?

**Comment by QiuMM** [comment]
In conclusion, I think current design of the load/drop rules is flexible and able to deal with almost all scenarios. But current `PeriodDropRule` is a impractical rule for it will always drop recent data. Then if people want to `retain 30 days` data, they can not use such `PeriodDropRule` but have to do like: load 30 days, drop forever. Because people have used the `drop forever` rule, then below things occured:
> 2. The user loads some data from slightly in the future (maybe some clocks are running a bit fast or slow) using streaming ingestion. This creates a segment with an interval that is in the future.
> 3. The coordinator disables the segment immediately upon noticing it (since it is not within the last 30 days).
> 4. The Kafka tasks time out during handoff (because the segments are never loaded).
> 5. And after that timeout, the data that was slightly in the future is still not available!
Then I think there are two way to solve these things:
1. Period load rules include the future by default
2. Add a new drop rule or modify current `PeriodDropRule` to support `drop before a period`, then if people want to `retain 30 days` data, they can do like this: drop 30 days before, load forever.

I prefer the second way and want to modify current `PeriodDropRule` not add a new one because the current one is very impractical, IMO no people would like to use such drop rule.

**Comment by QiuMM** [comment]
It's fine for me to keep current `PeriodDropRule`.  I'll open a PR to add such drop rule in a few days.

**Comment by jihoonson** [comment]
@QiuMM thanks!
