### ISSUE TITLE
Can we switch to Tez or Spark for batch ingestion ingestion instead of Map Reduce?

### ISSUE THREAD

**Issue by PrashantN86** [apache/incubator-druid#6003]
While going through druid documentation, I did not find any way to switch the batch ingestion from Map Reduce to Tez or Spark. Is it possible switch the execution engine to Tez or Spark as it can be done for Hive?

**Comment by Dylan1312** [comment]
Indexing is currently MapReduce only.

Metamarkets have a plugin that allows indexing via spark -> https://github.com/metamx/druid-spark-batch

**Comment by gianm** [comment]
@Dylan1312 is right, Druid doesn't currently support alternate execution engines out of the box. In addition to the metamx plugin there is also some work to have a built-in execution engine: #5492.

I will close this since I think your question is answered for now, but if you are interested in contributing in this area (maybe integrating a Spark engine into Druid core?) then please feel free to bring it up on the druid dev mailing list.

**Comment by drcrallen** [comment]
IMHO something like an apache beam focused indexing workflow would be more portable.
