### ISSUE TITLE
"Cannot have same delimiter and list delimiter of \u0001"

### ISSUE THREAD

**Issue by aoeiuvb** [apache/incubator-druid#6102]
When I used hadoop to absorb data, I used DelimitedParser to parse the row. The delimiter I set was **\u0001**, but the following error was reported to me:"**Cannot have the same delimiter and list delimiter of \u0001**".

I looked at the source code of the DelimitedParser and found that in the constructor, the delimiter and listDelimiter are checked to see if they are equal, and if so, an error will be reported.I did not set the value of listDelimiter, which is also the default value: **\u0001**, so this error was reported.To solve this problem, I specifically specified other values in the listDelimiter so that the program could pass.

May I ask if there is any problem with the design of this piece?
<img width="670" alt="_20180803210523" src="https://user-images.githubusercontent.com/15936294/43644856-be5ec84a-9762-11e8-8cb1-899a8bb02098.png">

**Comment by gianm** [comment]
Hi @aoeiuvb,

This behavior is intentional and is due to the fact that we have two kinds of delimiters: the field delimiter and a "list delimiter" within a field (in case your field is actually a list of separate values). The delimiters cannot be the same, since then we can't parse a row. I think setting the `listDelimiter` to some other value, like you did, is a good way to go.

**Comment by gianm** [comment]
Btw, I closed this since I think I answered your question, but feel free to post again if you are wondering something.
