### ISSUE TITLE
KafkaIndexTask can delete published segments on restart

### ISSUE THREAD

**Issue by jihoonson** [apache/incubator-druid#6124]
This can happen in the following scenario.

1. A kafka index task starts publishing segments.
2. The task succeeds to publish segments and is stopped immediately (by restarting the machine).
3. When the task is restored, it restores all sequences it kept in memory before restarting.
4. After reading some more events from Kafka, the task tries to publish segments. These segments include the ones which were published before restarting because the restored sequences contain them.
5. Since the segments which are published twice are already stored in metastore, the publish fails.
6. The set of published segments in metastore is different from the set of segments the task is trying because the task read more data.
7. The task thinks that the publish actually failed and removes the published segments from deep storage.

**Comment by gianm** [comment]
> 5. Since the segments which are published twice are already stored in metastore, the publish fails.

This doesn't seem right: there is code specifically to handle the case where a task tries to publish a segment that some task already published. It happens all the time with replicas, and they just ignore that segment and move on to the next one.

I wonder if the real reason for publish failure is that the startMetadata doesn't match up. I bet it wouldn't match up: it sounds like the task is trying to publish from the point it _originally_ started from rather than from the point it last published.

It sounds like there are two separate problems here:

- In (7) the task should not have removed the published segments (this is the biggest bug).
- In (3) the task should have done something smarter instead of restoring a setup that couldn't possibly work out.

**Comment by gianm** [comment]
I think this may be fixed by #6155, but would like to double-check that there are no lingering issues due to the fact that the sequences persist file and the appenderator persist file are separate files.

**Comment by jihoonson** [comment]
To make it clear, #6155 fixes Kafka tasks to not delete published segments any more. In the same scenario, the restored Kafka tasks would fail and the supervisor would respawn the new tasks which will finish the job.

**Comment by gianm** [comment]
Got it, I think we can close this then.

**Comment by jihoonson** [comment]
@gianm I think it makes sense to close this issue since the title is about kafka tasks deleting pushed segments. However, the tasks would still fail in the same scenario which can make users confused. Do you think we need to file this in another issue?
