### ISSUE TITLE
Druid load rule based on start date of segments

### ISSUE THREAD

**Issue by somanullah** [apache/incubator-druid#6387]
I have segments with segmentGranularity as DAY. As these segments are smaller in size, I used compaction task to combine all the segments for a month into a single segment. 
But since my load rule is defined for 30 days, this compacted segment got dropped which shouldnt have happened. It looks like load/drop rule checks only the start date of the segment before making its decision to drop it.
Ideally it should check if the end date of the segment is inside the load rule and make a decision based on that. Is this correct @jihoonson ?

**Comment by jihoonson** [comment]
Hi @somanullah, [Druid currently checks the segment interval overlaps with the rule's interval](https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/server/coordinator/rules/Rules.java#L30). Would you please tell more details about your rule spec and the total interval of the compacted segment?

**Comment by somanullah** [comment]
Hi @jihoonson My compacted segment interval is  2018-08-26 to 2018-09-26 and my load rule is P30D followed by drop forever. Since the start interval (2018-08-26) is now out of the period bounds, the segment got dropped. But the segment shouldn't have been dropped as it has data from dates which are within the load interval. Would it make better for the load rule to check the end date of the interval instead of the whole time interval overlaps?

**Comment by QiuMM** [comment]
@somanullah can you give more details about your compaction task's  payload as well as the load/drop  rules.

**Comment by licl2014** [comment]
Yep, we have same problem, our scenarios like the following:
1. I have load rules like: load 3 days, drop forever.
2. (today is 2018-10-11)My datasource has 4 days data and merged into one segment from **2018-10-08 to 2018-10-12**.
4. Because of the rule, the coordinator will drop that segment, in fact , we only want drop the data from **2018-10-08 to 2018-10-09**.

The related code in PeriodLoadRule.java is **currInterval.overlaps(intervial) && interval.getStartMillis() >= currInterval.getStartMillis()**, here ,   currInterval is **"2018-10-09/2018-10-12"**,  interval is **"2018-10-08/2018-10-12"**, "currInterval.overlaps(intervial)" is **true** and "interval.getStartMillis() >= currInterval.getStartMillis()" is **false**.

**Comment by QiuMM** [comment]
OK, I think I know why, you can merge code from master branch, in master there is no `interval.getStartMillis() >= currInterval.getStartMillis()` any more.

**Comment by licl2014** [comment]
@QiuMM Oh, thanks .

**Comment by somanullah** [comment]
Got it. Thanks

But it was very rude of @licl2014 to hijack my thread.

**Comment by jon-wei** [comment]
@somanullah There's not really a concept of a "thread owner", more comments, information, discussion are always welcome.
