### ISSUE TITLE
Support Join

### ISSUE THREAD

**Issue by weijietong** [apache/incubator-druid#6457]
This issue is to make Druid have the join ability. 

The main logic is to create a join index to represent the join relationship between joint tables. The joint tables should have the same number of shards which are generated according to their joint key,and stayed together. At Alipay, we achieved great query performance thorough this way.

 The related PRs will be split into several small parts: join sql translation , joint index segment generation, joint table schedule. It may take me some time to refactor my codes to adjust the community master code base.

**Comment by himanshug** [comment]
so the idea is that "joint tables" (that is tables to be joined together) will be sharded by same "join key" and special arrangements are made so that all shards for same join key for the "joint tables" goto same historical nodes and join can be done locally on historicals ?

**Comment by jihoonson** [comment]
Nice @weijietong! Would you please add some more details about your implementation which describes 1) how to specify joint tables, 2) how to locate the joint segments in the same historicals, and 3) how join algorithm works? It would be much helpful for reviewers.

I also have some questions about the goal of this issue.
-  Does this support join of realtime dataSources?
- One of the most common use cases is aggregation after join. `SELECT col, count(*) FROM t1, t2 WHERE t1.key = t2.key GROUP BY col` is an example sql. Does this support this kind of query?
- Does this support join of multiple dataSources?

**Comment by jihoonson** [comment]
@weijietong thanks for the answer! I think it's a good enough for starting support for join queries. I think there's no rush for making PR(s). 

I wonder https://github.com/apache/incubator-druid/issues/4040 is the proposal of this issue. Whether it is or not, I strongly recommend to write a new proposal for your idea, so that others can review its design first. (I guess the design and implementation might have been changed or new stuffs have been added since https://github.com/apache/incubator-druid/issues/4040 was written.) This is because this kind of work should be tagged with `Design Review` and get +1s from 3 different committers. The design review would also involve the review on the design of your implementation. According to the review comments, you may need to change some design decisions. This is always easier to do before fully writing your codes. Please check other proposals like https://github.com/apache/incubator-druid/issues/6319 or https://github.com/apache/incubator-druid/issues/4349.

**Comment by weijietong** [comment]
Sorry, I will leave the Druid community, so abort this work.

**Comment by gianm** [comment]
Sorry to hear that @weijietong.

**Comment by jason-heo** [comment]
@weijietong 

Really sorry to hear that.

> At Alipay, we achieved great query performance thorough this way.

I'm wondering if you have any plan open this feature publically so that one can continue your contribution.
