### ISSUE TITLE
Druid 0.13.0 | AWS SDK signature V2 soon out of life for some AWS regions?

### ISSUE THREAD

**Issue by Stephan3555** [apache/incubator-druid#6891]
Good morning,

we are currently switching from Druid 0.12.3 to Druid 0.13.0. With the new release the jets3t framwork was replaced with the AWS SDK. In the code we spot that druid is using the old signature version V2 for accessing the segments.

https://github.com/apache/incubator-druid/blob/druid-0.13.0-incubating/extensions-core/s3-extensions/src/main/java/org/apache/druid/storage/s3/S3Utils.java#L248

We are using currently eu-central-1 (EU Frankfurt) for our AWS S3. The AWS documantation states, that the used signature V2 is not compatible with EU Frankfurt and other regions. Seems like AWS is not officially supporting V2 for this region and can out of nothing deactivate it completely.

https://docs.aws.amazon.com/general/latest/gr/signature-version-2.html

Is there a plan to update the AWS SDK requests to V4?

Greetings,
Stephan

**Comment by peferron** [comment]
Are you referring to the `V2` in `ListObjectsV2Request` in the linked Druid source code? If so, I believe this `V2` just means that it's a revised version of the List Objects API, not that it's using Signature Version 2.

See the Python SDK docs where this is clearly mentioned: https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/s3.html#S3.Client.list_objects_v2

The Signature Version is configured separately, and all AWS SDKs appear to use Signature Version 4 by default since May 2016: https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#specify-signature-version

**Comment by Stephan3555** [comment]
Thanks for the explanation @peferron!
