### ISSUE TITLE
Wish list: Add the rowStats attributes of the columns of the sys.tasks table

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#7016]
Specifically `processed`, `processedWithError`, `thrownAway`, `unparseable`

This is currently available from the coordinator task report API but it would be amazing to be able to surface it via DruidSQL 

`"rowStats":{"buildSegments":{"processed":3630,"processedWithError":0,"thrownAway":0,"unparseable":0}}`

Then we could use all the cool SQL magic on it like filtering.

In particular we could surface it in the [new Druid console](https://github.com/apache/incubator-druid/issues/6832) Tasks view as a column:

![image](https://user-images.githubusercontent.com/177816/52314988-cf6f6600-2969-11e9-9249-09d1f311c457.png)

This will prevent the common confusion of "my task succeed but my where is my data (0 rows were ingested)

**Comment by surekhasaharan** [comment]
To get rowStats attributes of a task, the overlord api is documented [here](http://druid.io/docs/latest/ingestion/reports.html). In order to get rowStats for each task, we'll have to make a call to this api per task as part of the query. This could potentially slow down retrieval of tasks substantially because it would introduce a network hop for each task. We can speed up the queries by adding a cache, but not sure if it's worth the memory cost, the cache might add.
