### ISSUE TITLE
timeboundary should allow filters

### ISSUE THREAD

**Issue by pdeva** [apache/incubator-druid#702]
it is not particularly useful to know the time boundary of an entire datasource.
What is useful is to know the timeboundary of a certain condition. eg-

we allow multiple devices to connect to our service and store their metric data.
a timeboundary query that allowed us to filter on `deviceId=<id>` would let us know the begin and end timestamp of when a particular device started and stopped sending data.

**Comment by duaneatat** [comment]
This would be very useful. It's not possible for me to choose a granularity ahead of time because my timeseries data is filtered and spans an unknown part of the data source. As it is I have to do a recursive search where I make multiple calls to druid with increasing granularity to find the start and end time.

**Comment by vogievetsky** [comment]
I believe this is implemented: http://druid.io/docs/latest/querying/timeboundaryquery.html
@fjy I think this can be closed.
