### ISSUE TITLE
Kafka Ingestion Spec to allow kafka topic with gzip compression

### ISSUE THREAD

**Issue by coolboi567** [apache/incubator-druid#7039]
I have the following configuration in my ingestion script after following up with [this link](http://druid.io/docs/latest/development/extensions-core/kafka-ingestion.html).
```json
"tuningConfig": {
    "type": "kafka",
    "forceExtendableShardSpecs": true,
    "maxParseExceptions": 100,
    "maxSavedParseExceptions": 10,
    "indexSpec":{
      "dimensionCompression": "gzip",
      "metricCompression": "gzip"
    }
  }
```
While ingesting it says the following error, which make me realise that either gzip compression wasn't supported, or I was doing something wrong.
> {"error":"Can not construct instance of org.apache.druid.segment.data.CompressionStrategy, problem: No enum constant org.apache.druid.segment.data.CompressionStrategy.GZIP\n at [Source: HttpInputOverHTTP@5922d029[c=2248,q=0,[0]=null,s=STREAM]; line: 1, column: 2176] (through reference chain: org.apache.druid.indexing.kafka.supervisor.KafkaSupervisorSpec[\"tuningConfig\"]->org.apache.druid.indexing.kafka.supervisor.KafkaSupervisorTuningConfig[\"indexSpec\"]->org.apache.druid.segment.IndexSpec[\"dimensionCompression\"])" }

**Comment by peferron** [comment]
Do you mean that the Kafka messages themselves are compressed with gzip, either via a producer or broker configuration? If that's the case, then Druid can automatically handle decompression, just like most Kafka consumers. Try completely removing your `indexSpec` and giving it another shot.

`dimensionCompression` and `metricCompression` inside the `indexSpec` do not refer to how Druid decompresses messages from Kafka—they refer to how Druid compresses dimension and metric columns *after* consuming messages from Kafka. Decompression speed is usually critical there, which is why the doc lists `LZ4` and `LZF` as possible formats, but not `gzip`, which would be too slow.

**Comment by coolboi567** [comment]
I am not able to obtain data from Kafka the usual way.
After which, I assumed it wasn't able to handle the gzip compression.
Where can I see the actual logs of the event?

**Comment by coolboi567** [comment]
I am able to obtain data from other topics but the one with compression.

I had encountered similar problems when using [kafka-go by segmentio](https://github.com/segmentio/kafka-go) for the same topic, which I resolved by adding a [gzip extension](https://github.com/segmentio/kafka-go/tree/master/gzip).

**Comment by peferron** [comment]
If you download the [Kafka binary package](https://kafka.apache.org/downloads) on the same machine that runs your Druid middle manager process, are you able to read from this compressed topic using `kafka-console-consumer`?

Also, after removing the `indexSpec` from your ingestion spec, are you able to get a successful HTTP response code when submitting this ingestion spec? If yes, then you can try opening the [overlord console](http://druid.io/docs/latest/design/overlord.html) and look for the logs of the tasks corresponding to the compressed topic. If there are no tasks then look at the overlord logs directly to try to find out why.

**Comment by coolboi567** [comment]
I was able to consume data from `kafka-console-consumer`.
After removing `indexSpec` as well I was not able to ingest the topic or find anything suspicious in the logs.
Also, removing `useEarliestOffset` was the way to get it to work.
```
"useEarliestOffset": true
```

Thanks a lot for your help @peferron..

**Comment by coolboi567** [comment]
I am not sure what was the actual issue that I can see in the logs.
Because ingestion spec with `useEarliestOffset` worked fine on other topics.

Maybe it could be because of the 10 partitions with a lot of random starting offsets while a high rate of incoming messages to the topic.

**Comment by peferron** [comment]
Something that can happen quite easily also is if the previously committed offsets have been deleted in Kafka due to `log.retention.ms`. In this case the only way to unblock the Druid ingestion is to reset the supervisor, either via the overlord console or via API call. But in your case it looks like you didn't need to do that, so I'm not sure what the problem was.
