### ISSUE TITLE
isAvailable is always default in SegmentMetadataHolder

### ISSUE THREAD

**Issue by leventov** [apache/incubator-druid#7305]
From the code, `isAvailable` field in this class can never be anything but the default value. This might be a bug.

FYI @surekhasaharan

**Comment by jihoonson** [comment]
@leventov `SegmentMetadataHolder` is for metadata of segments announced by historicals or realtime tasks. So, `isAvailable` is always true for those segments. `SegmentsTable.scan()` in `SystemSchema` is to create the real result.

I understand it is not clear how system schema works. Maybe it's because of the lack of javadocs and comments. @surekhasaharan do you have any idea to make it more easily understandable?

**Comment by leventov** [comment]
Then the class may better be called `AvailableSegmentMetadata` (I don't see much sense in `Holder` endings everywhere in the codebase) and `isAvailable` field removed.

**Comment by leventov** [comment]
Or "LoadedSegmentMetadata".

**Comment by jihoonson** [comment]
It sounds good to me to remove `isAvailable` field. Regarding naming, I think `AvailableSegmentMetadata` is better because it is also for segments announced by realtime tasks.

**Comment by surekhasaharan** [comment]
@leventov `AvailableSegmentMetadata` seems good to me as well, yeah I added `holder` probably by looking around at rest of the code base. @jihoonson will try to add more javadocs in the refactoring PR.

**Comment by surekhasaharan** [comment]
It seems `isPublished` is also not changed, perhaps both `isAvailable` and `isPublished` can be removed from `SegmentMetadataHolder` or `AvailableSegmentMetadata`.

**Comment by gianm** [comment]
Closed by #7372.
