### ISSUE TITLE
Are there documentation on the limitation of intersection using theta sketch?

### ISSUE THREAD

**Issue by jltqst27** [apache/incubator-druid#7444]
Not sure if this is the right place to ask this but I am testing set intersection on druid using theta sketch, but I am having trouble producing result with good accuracy after the third intersection.

        UpdateSketch sketch1 = UpdateSketch.builder().setLogNominalEntries(12).build();
        UpdateSketch sketch2 = UpdateSketch.builder().setLogNominalEntries(12).build();
        UpdateSketch sketch3 = UpdateSketch.builder().setLogNominalEntries(12).build();
        UpdateSketch sketch4 = UpdateSketch.builder().setLogNominalEntries(12).build();
        UpdateSketch sketch5 = UpdateSketch.builder().setLogNominalEntries(12).build();

        Set<Integer> k1 = new HashSet<>();
        Set<Integer> k2 = new HashSet<>();
        Set<Integer> k3 = new HashSet<>();
        Set<Integer> k4 = new HashSet<>();
        Set<Integer> k5 = new HashSet<>();

        Random rand = new Random();

        for (int key = 0; key < 3400000; key++) {
            int n1 = rand.nextInt(20000000);
            int n2 = rand.nextInt(20000000);
            int n3 = rand.nextInt(20000000);
            int n4 = rand.nextInt(20000000);
            int n5 = rand.nextInt(20000000);

            sketch1.update(n1);
            sketch2.update(n2);
            sketch3.update(n3);
            sketch4.update(n4);
            sketch5.update(n5);
            k1.add(n1);
            k2.add(n2);
            k3.add(n3);
            k4.add(n4);
            k5.add(n5);
        }

        int count1_2 = 0;
        int count1_2_3 = 0;
        int count1_2_3_4 = 0;
        int count1_2_3_4_5 = 0;
        for(Integer k: k1) {
            if (k2.contains(k)) {
                count1_2 += 1;
            }

            if (k2.contains(k) && k3.contains(k)) {
                count1_2_3 += 1;
            }

            if (k2.contains(k) && k3.contains(k) && k4.contains(k)) {
                count1_2_3_4 += 1;
            }

            if (k2.contains(k) && k3.contains(k) && k4.contains(k) && k5.contains(k)) {
                count1_2_3_4_5 += 1;
            }
        }

        Intersection intersection = SetOperation.builder().buildIntersection();
        intersection.update(sketch1);
        Sketch intersectionResult1 = intersection.getResult();
        intersection.update(sketch2);
        Sketch intersectionResult1_2 = intersection.getResult();
        intersection.update(sketch3);
        Sketch intersectionResult1_2_3 = intersection.getResult();
        intersection.update(sketch4);
        Sketch intersectionResult1_2_3_4 = intersection.getResult();
        intersection.update(sketch5);
        Sketch intersectionResult1_2_3_4_5 = intersection.getResult();

        System.out.println(count1_2);
        System.out.println(count1_2_3);
        System.out.println(count1_2_3_4);
        System.out.println(count1_2_3_4_5);
        System.out.println(intersectionResult1_2.toString());
        System.out.println(intersectionResult1_2_3.toString());
        System.out.println(intersectionResult1_2_3_4.toString());
        System.out.println(intersectionResult1_2_3_4_5.toString());
        System.out.println(intersectionResult1.toString());

Is there a documentation about what kind of result we can expect for intersection?

**Comment by leerho** [comment]
Refer to documentation [here](https://datasketches.github.io/docs/Theta/ThetaSketchSetOps.html) and [here](https://datasketches.github.io/docs/Theta/ThetaAccuracyPlots.html).

When you print the results via toString() you should be able to see the 95% confidence upper and lower bounds from the sketch itself.  What the sketch is telling you is that given the configuration of your sketches and the cardinalities of your input streams, the "true" answer should be within those bounds with 95% confidence.  And theoretically this is the best you can do given the above.

Theta sketches retain only a small sample of the input streams that that they see.  When you perform an intersection it reduces that small sample to an even smaller set, possibly zero!  And as you might guess, extracting useful information about your input streams with zero samples is rather difficult:

![We_do_sketches](https://user-images.githubusercontent.com/12941506/55978742-66e08600-5c45-11e9-9721-e746dafc7e87.png)

Successive intersections will quickly reduce your number of samples available to estimate from and thus will dramatically increase the error.  Also attempting to intersect one sketch from a large cardinality set with another sketch from a very small cardinality set will also increase your error (see the 2nd link above).  

**So what can you do?**

- Organize your intersections (and AnotB ops) to be performed as the very last step.  For example,
instead of `AU(B^C)` use `(AUB)^(AUC)`. This keeps the internal sample set as large as possible until the very end.
- If you know which streams have large cardinality, use large sketches for these sketches. Internally we use sketches of 2^20 for our large cardinality streams (there is generally only a few of them) and then 2^14 for everything else.
- Always query the resulting sketch from a set expression to obtain the upper and lower bounds.   This will tell you right away what your error confidence interval is.
