### ISSUE TITLE
Garbage collection occurs frequently at historical node

### ISSUE THREAD

**Issue by aoeiuvb** [apache/incubator-druid#7476]
Garbage collection occurs frequently at historical node

### Affected Version

0.12.1

### Description
Garbage collection happens every two seconds. What's going on? What should I do about it
<img width="699" alt="6b54bab8b4ff889705368b72a64ebbc" src="https://user-images.githubusercontent.com/15936294/56139685-eff01800-5fcb-11e9-9a1b-55ab1491ecdc.png">

**Comment by gianm** [comment]
Those collections aren't taking a ton of time, so if they aren't affecting your overall performance, they might not be a big deal. If you want to try to optimize them then standard Java GC tuning techniques would apply (possibly changing the collector implementation or changing the parameters for your collector). Also updating to later Druid version might help, since we often make changes to try to improve GC behavior.

**Comment by aoeiuvb** [comment]
When garbage collection occurs, druid queries slow down, and when there is no garbage collection, the queries are fast and stable

**Comment by aoeiuvb** [comment]
> Those collections aren't taking a ton of time, so if they aren't affecting your overall performance, they might not be a big deal. If you want to try to optimize them then standard Java GC tuning techniques would apply (possibly changing the collector implementation or changing the parameters for your collector). Also updating to later Druid version might help, since we often make changes to try to improve GC behavior.

When garbage collection occurs, druid queries slow down, CPU usage is also higher,and when there is no garbage collection, the queries are fast and stable
