### ISSUE TITLE
Enable SQL by default

### ISSUE THREAD

**Issue by yurmix** [apache/incubator-druid#7793]
### Description

According to #3682, SQL is disabled by default to save additional metadata queries by the broker (Per new segment, not per query).

However, I think that since SQL is no longer considered experimental, we should enable SQL by default (set the default of `druid.sql.enable` to `true`). 

If there is any performance optimization needed to be done, we should probably do it anyways (if SQL is to be broadly adopted).

I admit this could lead to cluster operators getting unexpected SQL queries from end users. However, if clearly documented in release notes, operators can simply disable through configuration.

### Motivation

* Increase adoption by letting end users easier access to SQL.
* Bring SQL one step closer to a first-class citizen.

**Comment by vogievetsky** [comment]
It should also be noted that the new web console heavily relies on SQL and while the functionality is there to make it work without SQL having SQL enabled unlocks many of its features due to the heavy use of Druid system tables

**Comment by gianm** [comment]
I think the only real downside is that there will be slightly more load on historicals (due to extra metadata queries) and memory use on the broker will be somewhat higher (enabling SQL activates a metadata cache). But these effects should be small and I think they are worth it, since SQL is rad. So I think enabling it by default is good. By the way, most of our customers (at Imply) have SQL enabled.

SQL can only do things that native queries could also do (they simply translate into native queries) so I don't think cluster operators getting unexpected SQL queries would be a serious issue.
