### ISSUE TITLE
Single server Druid quickstart should not need Zookeeper

### ISSUE THREAD

**Issue by vogievetsky** [apache/incubator-druid#7884]
### Description

The current quickstart requires an extra step to download and unpack zookeeper.

![image](https://user-images.githubusercontent.com/177816/59413237-091b0800-8d74-11e9-8128-4087d932231d.png)

Could ZK be part of the Druid bundle so there are 3 fewer steps to the quickstart?

### Motivation

Fewer quickstart steps = more people getting through the quickstart.

Also bundling ZK seems to be common in other similar projects... so... peer pressure!

**Comment by a2l007** [comment]
Due to some of the known issues with ZK, I believe there is an effort to reduce ZK dependency as much as possible. Relevant PRs/issues:
#5104 #4966 #2312
https://groups.google.com/forum/#!msg/druid-development/eIWDPfhpM_U/AzMRxSQGAgAJ

Wouldn't bundling ZK along with Druid push us in the opposite direction?

**Comment by fjy** [comment]
Agree with @vogievetsky. We're far away from removing our ZK dependency and it should be bundled with Druid.

**Comment by vogievetsky** [comment]
This is fixed by #8792 🎆
