### ISSUE TITLE
Confusing Scan Query example

### ISSUE THREAD

**Issue by dinsaw** [apache/incubator-druid#7895]
As a beginner user of Druid, I find [Scan Query Example
](https://druid.apache.org/docs/latest/querying/scan-query.html) confusing.

The example scan query is 

> {
   "queryType": "scan",
   "dataSource": "wikipedia",
   "resultFormat": "list",
   "columns":[],
   "intervals": [
     "2013-01-01/2013-01-02"
   ],
   "batchSize":20480,
   "limit":5
 }

Here, `batchSize` is greater than `limit`, which does not make sense. Why will we load  20480 records in memory to return just 5 records. I guess adding filter to this example will add more clarity.

We can change the query to 
```
{
  "queryType": "scan",
  "dataSource": "wikipedia",
  "resultFormat": "list",
  "columns": [],
  "intervals": [
    "2013-01-01/2013-01-02"
  ],
  "filter": {
    "type": "in",
    "dimension": "page",
    "values": [
      "Justin Bieber"
    ]
  },
  "batchSize": 20480,
  "limit": 50
}
```

With filter criteria, The reader can infer that **filtering criteria will be applied on batch of 20480 records and result will be returned to client. If first batch filtering does not return 50 records then the next batch of 20480 records will be fetched to fulfil limit parameter. This process will happen again and again until the returned rows count is 50 or all rows are scanned**

**Comment by justinborromeo** [comment]
Hi Dinesh,

I think you misunderstand how the scan query is implemented.  Afaik, filtering using the index(es) occurs prior to batching.  When the historical reads rows into a batch (see `ScanQueryLimitRowIterator.java` for reference), this batch only contains filtered records.  Then, batches of `batchSize` rows are streamed back to the broker until `limit` rows have been returned (the only edge case being the last batch which might contain fewer than `batchSize` rows to avoid exceeding `limit`).

This differs from your understanding in that you're assuming that every row is being scanned and filtered through.  Rather than combining rows into batches prior to filtering, batching is used to combine results **after filtering** to be streamed back.

Referring to the doc example, the `batchSize` property actually corresponds to a **maximum** batch size. Perhaps the property could be named better but it's too much pain to change the API for minimal benefit.

**Comment by dinsaw** [comment]
Thanks @justinborromeo to clear my understanding.
