### ISSUE TITLE
CompressionUtils performance improvement ask

### ISSUE THREAD

**Issue by crodier** [apache/incubator-druid#7932]
FileUtils, needs (on or around line 234), a BufferedOutputStream instead of a FilterOutputStream (we think.)  Apologies for not submitting a proper patch.

### Affected Version

0.14.2-incubating

### Description

When we compress a 20mb smoosh folder today into a zip.  It takes about 15 seconds, whereas the previous implementation of Compression Utils takes about a second.  This makes the hand-off compression much slower.

The software is amazing, thank you.

**Comment by himanshug** [comment]
what was the version where same zipping operation was taking 1 second ?

If you use "local" deep storage then I "guess" it could be due to explicit "fsync" that was enabled sometime last year and could be really responsible for this time. but that was done to fix corruption issues.

**Comment by crodier** [comment]
Yes, local deep storage, to a disk drive.  The "atomic" update yes, which was enabled last year, made it 20x slower.  You can still do the atomic update, but need to use the Buffered stream, not FilterOutput stream.

**Comment by himanshug** [comment]
I think https://github.com/apache/incubator-druid/pull/6677 is the PR in question. that PR  didn't change anything wrt use[or no use] of buffered output steam, only change introduced is to write to temp file instead of final file and do an fsync . so not sure why that specific change caused perf to go 20x slower (if fsync() is not the problem)
can you point to the change that removed usage of Buffered OutputStream that is causing the slowness ?

**Comment by gianm** [comment]
It's possible the change from FileOutputStream to FileChannel on https://github.com/apache/incubator-druid/pull/6677/files#diff-8cbeaa1874f0c7db8634387441433351L81 had some effect. Maybe FileOutputStream does buffering differently from the OutputStream you get by doing `Channels.newOutputStream(fileChannel)`?

**Comment by crodier** [comment]
#5344 seems to have it?  Should be using something other than, FilterOutputStream?

https://github.com/apache/incubator-druid/pull/5344#pullrequestreview-257485887

https://stackoverflow.com/questions/47721200/javas-filteroutputstream-adds-a-performance-penalty

Hope this helps, and we meet one day at an event, terrific software, ty!

**Comment by himanshug** [comment]
@crodier thanks . ok, I see now. FilterOutputStream default `FilterOutputStream.write(byte b[], int off, int len)` default impl is dumber than it needs to be.
In this case, Performance degradation is not related to BufferedOutputStream which we never had in that context but due to the use of FilterOutputStream  . I did some tests and https://github.com/apache/incubator-druid/pull/8024 should fix the regression.

**Comment by gianm** [comment]
Thanks for the investigation @himanshug & @crodier!!
