### ISSUE TITLE
KIS: potential data overriding when taskDuration is set

### ISSUE THREAD

**Issue by litao91** [apache/incubator-druid#7949]
### Affected Version

Since KIS was introduced 

### Description

Consider the following case

1. We have a KIS generates a segment of 12:00-13:00, of version v1
2. At 12:30 the all the sub tasks come to the end of duration and release the locks at nearly the same time. 
3. New subtasks start and create new segment, also of interval 12:00-13:00. Since we have to acquire new lock for new tasks, the segment have new version of v2
4. Then, the same interval of v2 will overshadow that of v1, which is unexpected.

**Comment by jihoonson** [comment]
Hi @litao91, did you see any data loss because of the described problem? I'm asking because this shouldn't happen. What should happen in KIS is,

1) First generation of Kafka tasks generates segments of interval of 12:00-13:00, of version v1.
2) Next generation tasks starts and creates new segments, also of interval of 12:00-13:00. At this point, they would lock those segments with the version _v2_.
4) However, those segments themselves will have the version _**v1**_, not v2, since they shouldn't override existing segments.
4) Once the new segments are published, both existing and new segments end up being available in historicals.

**Comment by litao91** [comment]
@jihoonsoon thanks! No, I haven’t really encountered data loss. I’m asking because one of our scenario needs a short taskDuration and I’m thinking about the feasibility.

Just curious, how the kafka task know that the version should be v1 instead of v2? Doesn’t the segment take the version directly from the lock?

Thanks

**Comment by jihoonson** [comment]
Good to hear that this is not a real issue.

In KIS, the overlord is responsible for allocating segments and it chooses the segment version as below:

1) If this is the first segment for the given interval, it chooses the lock version as the segment version.
2) If there are existing segments in the given interval, it chooses the max version of existing segments as the version of the new segment.

This is implemented here: https://github.com/apache/incubator-druid/blob/master/server/src/main/java/org/apache/druid/metadata/IndexerSQLMetadataStorageCoordinator.java#L613-L713

**Comment by litao91** [comment]
I see. Thanks a lot!
