### ISSUE TITLE
druid indexer running Kafka indexing not seen as dataSource

### ISSUE THREAD

**Issue by sixtus** [apache/incubator-druid#8710]
I just spent 2.5h figuring out why I am not seeing any realtime data using the new indexer nodes.

And here it is:

```druid-broker[10249]: WARN [CuratorDruidNodeDiscoveryProvider-ListenerExecutor] org.apache.druid.discovery.DruidNodeDiscoveryProvider$ServiceDruidNodeDiscovery - Node[DiscoveryDruidNode{druidNode=DruidNode{serviceName='druid/indexer', host='indexer.node', bindOnHost=false, port=-1, plaintextPort=8091, enablePlaintextPort=true, tlsPort=-1, enableTlsPort=false}, nodeType='INDEXER', services={workerNodeService=WorkerNodeService{ip='...', capacity=64, version='1'}, lookupNodeService=LookupNodeService{lookupTier='__default'}}}] discovered but doesn't have service[dataNodeService]. Ignored.```

### Affected Version

0.16

### Description

Brokers (and coordinators for UI) ignore the new indexer nodes when using http segment announcement (didn't try batch).

I had to revert to middle manager. It was the feature I upgraded for... oh well, shouldn't be hard to fix.

**Comment by clintropolis** [comment]
I am able to replicate this issue locally, and [this modification](https://github.com/apache/incubator-druid/compare/master...clintropolis:indexer-http-inventory-fix) fixes the problem since it modifies the indexer to announce itself as a `dataNodeService`, but I'm unsure how to write tests for it so haven't opened a PR yet.

MiddleManager nodes do not have this problem because tasks that are not running on an Indexer [perform this announcement themselves](https://github.com/apache/incubator-druid/blob/master/indexing-service/src/main/java/org/apache/druid/indexing/seekablestream/SeekableStreamIndexTaskRunner.java#L394), since it is per task. Indexers rightfully suppress this but were lacking a replacement.
