### ISSUE TITLE
How to set the druid replication to zero?

### ISSUE THREAD

**Issue by abk-code** [apache/incubator-druid#8842]
I have a working POC with ingestion going on and see replication =2 on the published segments and replication=1 on unpublished segments when seen on the console. I think this is adding up the disk size used up on the cluster which we would like to reduce. I want to set the replication to zero so that lesser disk space is used since we are writing the data to S3 (backend) anyways.  What is the setting I need to use and which spec file?

Also, what is the best compression ? Default compression is LZ4. Is there any better compression that we could use to reduce the disk usage? 

thanks

**Comment by gianm** [comment]
Hi @abk-code,

The lowest replication you can set is 1. Zero isn't allowed since it would mean no copies of data exist on the Druid servers, and Druid always queries data from local disk or local memory. (Even though there is a copy on S3, the querying always happens from local disk/memory.)

The default compression settings generally compress the most aggressively. Usually people change away from the defaults if they want higher scan rates but a lower compression level.

One really good way to reduce footprint is to consider the optimal partitioning and sorting of your data: https://druid.apache.org/docs/latest/ingestion/index.html#partitioning

Rollup is also useful: https://druid.apache.org/docs/latest/ingestion/index.html#rollup

**Comment by abk-code** [comment]
Thanks @gianm : Can you please let me know the exact file / setting to set the replication to 1.

**Comment by rachelpedreschi** [comment]
They are configured in the Load Rules:
https://druid.apache.org/docs/latest/operations/rule-configuration.html

**Comment by gianm** [comment]
You can also configure it in the console's "Datasources" tab under "Retention". (see below)

![image](https://user-images.githubusercontent.com/1214075/68434657-5d34e780-016e-11ea-84a4-76b9c7532075.png)

**Comment by abk-code** [comment]
awesome,thank you!

**Comment by vogievetsky** [comment]
Closing as resolved 🎆
